name: TaberAddon-Nickname
author: Samuel Taber and Joshua Hanson
version: 0.1
main: com.tabercore.main.Nickname
commands:
    nickname:
        aliases: [nick]
        description: Nicknames a player.